# name: Build

# on:
#   push:
#     branches: 
#       - "main"
#     paths-ignore:
#       - "README.md"

# jobs:
#   build:
#     runs-on: windows-latest
#     permissions: write-all
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: "recursive"

#       - uses: Jimver/cuda-toolkit@v0.2.16
#         id: cuda-toolkit
#         with:
#           cuda: "12.5.0"

#       - name: Bump version, push tag
#         id: tags
#         uses: mathieudutour/github-tag-action@v6.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}

#       - name: Create project folder
#         run: cmake -E make_directory proj

#       - name: Generate
#         working-directory: ${{github.workspace}}\proj
#         run: cmake ../ -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_VERSION="v${{ steps.tags.outputs.new_version }}"

#       - name: Build
#         working-directory: ${{github.workspace}}\proj
#         run: cmake --build . --config MinSizeRel

#       - name: Compress
#         working-directory: ${{github.workspace}}\proj\MinSizeRel
#         run: 7z a source-diffusion.zip "Source diffusion.exe" source-diffusion.dll

#       - name: Release
#         uses: softprops/action-gh-release@v1
#         with:
#           body: ${{ steps.tags.outputs.changelog }}
#           tag_name: v${{ steps.tags.outputs.new_version }}
#           name: "v${{ steps.tags.outputs.new_version }}"
#           fail_on_unmatched_files: true
#           files: |
#             proj/MinSizeRel/source-diffusion.zip
